### ISSUE TITLE
Same shoe keep posting every second (SNKRS)

### ISSUE THREAD

**Issue by cens6r** [yasserqureshi1/Sneaker-Monitors#109] opened 2021-09-13 05:22 UTC
**Describe the bug**
The webhook keeps posting the same shoe, same context except for size. Every single second.

**To Reproduce**
1. Set LOCATION to US, LOC to US, LAN to en in the .env file
2. Set DELAY to 3
3. No Proxy, Keywords
4. Infinite Loop of the same shoe (AIR MAX BW OG)
5. The link for the shoe dosen't work too.

**Expected behavior**
Actual Restock, Launch, Sold Out Notifications, etc.

**Screenshots**
[Image](https://cdn.discordapp.com/attachments/886835713860042813/886844190724595752/unknown.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 21H2 22000.176
 - Client: Discord Canary (I tried using normal discord webhook link too but same problem)
 - Version: 97052 (4fa7542) Host 1.0.40

**Additional context**
Am I doing anything wrong?

**Comment by king1267** [comment] 2021-10-07 00:48
Same for me, that exact same shoe too.

**Comment by kacperkwapisz** [comment] 2021-11-18 15:41
Hello, could you tell me if the issue is still applicable?

**Comment by king1267** [comment] 2021-11-21 01:10
Hi, no I no longer get that issue but now when I run it, the testing
Webhook posts in my discord but only that and none of the shoes on Nike
SNKRS. I get
Anchor 60
Anchor 120
Anchor 180
repeated over and over again. Is there any way to make it post all the new
shoes on SNKRS?

Thank You,
King

**Comment by yasserqureshi1** [comment] 2021-11-21 14:15
> 

So it monitors the top 180 most recent products. This is because you can only request for 60 products at a time so to ensure speed and lower the number of requests, I chose 180. So it prints the anchor for every api call it makes. It should then post newly released shoes or restocks of the top 180 products. 

I'll close this issue now

**Closed as completed by yasserqureshi1** 2021-11-21 14:15 UTC
