### ISSUE TITLE
Brazilian Set-up

### ISSUE THREAD

**Issue by Codeff3** [yasserqureshi1/Sneaker-Monitors#71] opened 2021-03-23 12:08 UTC
how do I do pro monitor work in Brazil I need some link from nike API?

**Comment by Thjisio** [comment] 2021-03-26 19:52
Hi,

You need an API link. Besides that, the developer has not looked in to the framework of NIKE Brazil, so there might be more recoding needed for it to actually function for that region.

**Comment by yasserqureshi1** [comment] 2021-05-10 00:14
Closing as this is a duplicate of #25

**Closed as completed by yasserqureshi1** 2021-05-10 00:14 UTC
Labels: new monitor
